/**
 * Prints the exact command the full-hardware pipeline would run, built by the
 * real factory against real library rows, and emits a runnable script that
 * executes it briefly against a temporary output directory.
 *
 * Run this on a development machine — it needs src/ and the media database,
 * neither of which is in the runtime image. It executes nothing itself: the
 * generated script is what you copy into the container, where the media engine
 * and the media files actually are.
 *
 *   bun run scripts/hardware-pipeline-dry-run.ts --db /mnt/tower/appdata/toasttv/media.db
 *   docker cp /tmp/hardware-pipeline-dry-run.sh ToastTV:/tmp/dry.sh
 *   docker exec -it ToastTV bash /tmp/dry.sh
 *
 * What it is looking for is not a crash. A graph missing `format=nv12` exits
 * zero having written nothing at all, so the generated script checks that
 * segments appeared and reports their size.
 */

import { Database } from 'bun:sqlite'
import { FfmpegHardwareHlsPipelineFactory } from '../src/services/FfmpegHardwareHlsPipelineFactory'
import type {
  ChannelPipelineRequest,
  ChannelTimelinePosition,
} from '../src/services/ContinuousChannelWorkerManager'

const args = process.argv.slice(2)
const option = (name: string, fallback: string): string => {
  const index = args.indexOf(`--${name}`)
  return index >= 0 ? (args[index + 1] ?? fallback) : fallback
}

const databasePath = option('db', '/mnt/tower/appdata/toasttv/media.db')
const outputScript = option('out', '/tmp/hardware-pipeline-dry-run.sh')
const itemCount = Number(option('items', '3'))
const seconds = Number(option('seconds', '20'))

const HARDWARE_CODECS = ['h264', 'hevc', 'av1', 'vp9', 'mpeg2video']

const db = new Database(databasePath, { readonly: true })

/*
 * A representative window rather than an easy one: the mix that actually
 * reaches the graph is a programme plus the station assets around it, and the
 * pillarbox path only appears when something is not already 16:9.
 */
function pick(where: string, limit: number): Array<Record<string, unknown>> {
  return db
    .prepare(
      `SELECT path, codec, width, height, pixel_format, duration_seconds, has_audio
       FROM media
       WHERE ${where}
         AND root_available = 1
         AND codec IN (${HARDWARE_CODECS.map((c) => `'${c}'`).join(',')})
         AND pixel_format IS NOT NULL AND pixel_format <> ''
         AND width > 0 AND height > 0
         AND duration_seconds > 0
       ORDER BY id LIMIT ?`
    )
    .all(limit) as Array<Record<string, unknown>>
}

const widescreen = pick("media_type <> 'interlude' AND width = 1920 AND height = 1080", 1)
const pillarboxed = pick("media_type <> 'interlude' AND width * 1080 <> height * 1920", 1)
const assets = pick("media_type = 'interlude'", Math.max(1, itemCount - 2))
const rows = [...widescreen, ...pillarboxed, ...assets].slice(0, itemCount)

if (rows.length === 0) {
  console.error(
    `No eligible rows in ${databasePath}.\n` +
      'If pixel_format is empty across the library the probe backfill has not run yet, ' +
      'and every window would fall back to software.'
  )
  process.exit(1)
}

const sequence: ChannelTimelinePosition[] = rows.map((row, index) => ({
  scheduleItemId: `dry-run-${index}`,
  sourcePath: String(row.path),
  sourceOffsetSeconds: 0,
  sourceDurationSeconds: Math.min(Number(row.duration_seconds), 30),
  hasAudio: row.has_audio === null ? undefined : row.has_audio === 1,
  decodeHint: 'hw',
  sourceWidth: Number(row.width),
  sourceHeight: Number(row.height),
  timelineRevision: 'dry-run',
  type: index === 0 ? 'program' : 'interlude',
})) as ChannelTimelinePosition[]

const request = {
  channelId: 'dry-run',
  sequence,
  position: sequence[0],
  profile: {
    videoCodec: 'h264',
    audioCodec: 'aac',
    audioChannels: 2,
    segmentSeconds: 2,
    playlistWindowSegments: 8,
    maximumWidth: 1920,
    maximumHeight: 1080,
  },
  outputDirectory: '/tmp/dry-run-hls',
  playlistPath: '/tmp/dry-run-hls/live.m3u8',
  appendToExistingPlaylist: false,
} as unknown as ChannelPipelineRequest

const factory = new FfmpegHardwareHlsPipelineFactory(
  'ffmpeg',
  undefined,
  undefined,
  undefined,
  { activeBackend: 'intel-qsv', device: '/dev/dri/renderD128' } as never
)

console.log('Window:')
for (const item of sequence) {
  console.log(
    `  ${item.sourceWidth}x${item.sourceHeight}  ${String(item.sourcePath)}`
  )
}
console.log(`\nEligible as one window: ${factory.eligible(request)}\n`)

const command = factory.command(request)
console.log('Command:\n')
console.log(command.map((part) => (/[ ;[\]]/.test(part) ? `'${part}'` : part)).join(' '))

const quoted = command
  .map((part) => `'${String(part).replace(/'/g, `'\\''`)}'`)
  .join(' ')

await Bun.write(
  outputScript,
  `#!/usr/bin/env bash
# Generated by scripts/hardware-pipeline-dry-run.ts — run inside the container.
set -u
OUT=/tmp/dry-run-hls
rm -rf "$OUT"; mkdir -p "$OUT"

echo "Running the full-hardware graph for ${seconds}s..."
timeout ${seconds} ${quoted}
status=$?
echo
echo "ffmpeg exit: $status  (124 means the timeout stopped it, which is expected)"

segments=$(ls -1 "$OUT"/segment-*.ts 2>/dev/null | wc -l)
bytes=$(du -sb "$OUT" 2>/dev/null | cut -f1)
echo "segments written: $segments"
echo "bytes written:    \${bytes:-0}"
echo
if [ "$segments" -gt 0 ] && [ "\${bytes:-0}" -gt 10000 ]; then
  echo "PASS  the graph produced real output"
  echo
  head -12 "$OUT/live.m3u8" 2>/dev/null
else
  echo "FAIL  no output. This is the silent failure mode: a graph missing"
  echo "      format=nv12 exits cleanly having written nothing. Re-run the"
  echo "      command above without 'timeout' to see ffmpeg's own warnings."
fi
`
)
console.log(`\nWrote ${outputScript}`)
console.log(`Next:\n  docker cp ${outputScript} ToastTV:/tmp/dry.sh && docker exec -it ToastTV bash /tmp/dry.sh`)
